/**
 * Main NLP-to-Cypher translator.
 *
 * 1. First tries to match against pre-built query templates (fast path).
 * 2. If no template matches, uses Claude via the Anthropic SDK to generate Cypher.
 * 3. Validates the generated Cypher before returning.
 */

import Anthropic from "@anthropic-ai/sdk";
import { SCHEMA_CONTEXT } from "./schema-context.js";
import { matchTemplate } from "./query-templates.js";
import { validateCypher, type CypherValidation } from "./cypher-validator.js";

export interface TranslationResult {
  query: string;
  cypher: string;
  source: "template" | "llm";
  explanation: string;
  validation: CypherValidation;
}

export interface TranslatorOptions {
  apiKey?: string;
  model?: string;
}

const SYSTEM_PROMPT = `You are a Cypher query generator for a code analysis Neo4j graph database.

${SCHEMA_CONTEXT}

## Rules
- Generate ONLY valid, read-only Cypher queries.
- NEVER use CREATE, MERGE, DELETE, DETACH, REMOVE, SET, or DROP.
- Always include a RETURN clause.
- Use parameterized-style names where appropriate but output concrete Cypher (no $params).
- Wrap your Cypher query in a code block with \`\`\`cypher and \`\`\` delimiters.
- After the code block, provide a one-sentence explanation of what the query does.
`;

/**
 * Extract a Cypher query from an LLM response that may contain markdown code blocks.
 */
function extractCypher(response: string): { cypher: string; explanation: string } {
  // Try to extract from ```cypher ... ``` block
  const codeBlockMatch = response.match(/```(?:cypher)?\s*\n([\s\S]*?)```/);
  if (codeBlockMatch) {
    const cypher = codeBlockMatch[1].trim();
    // Everything after the code block is the explanation
    const afterBlock = response.slice(response.indexOf("```", codeBlockMatch.index! + 3) + 3).trim();
    return { cypher, explanation: afterBlock || "Generated by LLM" };
  }

  // Fallback: treat the entire response as Cypher
  return { cypher: response.trim(), explanation: "Generated by LLM" };
}

/**
 * Translate a natural language question about the codebase into a Cypher query.
 */
export async function translateToCypher(
  question: string,
  options?: TranslatorOptions,
): Promise<TranslationResult> {
  // Fast path: try template matching first
  const templateResult = matchTemplate(question);
  if (templateResult) {
    const validation = validateCypher(templateResult.cypher);
    return {
      query: question,
      cypher: templateResult.cypher,
      source: "template",
      explanation: templateResult.description,
      validation,
    };
  }

  // LLM path: requires API key
  const apiKey = options?.apiKey ?? process.env.ANTHROPIC_API_KEY;
  if (!apiKey) {
    throw new Error(
      "No template matched and no Anthropic API key provided. " +
        "Set the ANTHROPIC_API_KEY environment variable or pass apiKey in options.",
    );
  }

  const model = options?.model ?? "claude-sonnet-4-20250514";
  const client = new Anthropic({ apiKey });

  const response = await client.messages.create({
    model,
    max_tokens: 1024,
    system: SYSTEM_PROMPT,
    messages: [{ role: "user", content: question }],
  });

  const textBlock = response.content.find((block) => block.type === "text");
  if (!textBlock || textBlock.type !== "text") {
    throw new Error("LLM returned no text content");
  }

  const { cypher, explanation } = extractCypher(textBlock.text);
  const validation = validateCypher(cypher);

  return {
    query: question,
    cypher,
    source: "llm",
    explanation,
    validation,
  };
}
